# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

# Generated by Django 6.0.3 on 2026-03-12 20:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [("django_regional", "0006_country_default_currency")]

    operations = [
        migrations.CreateModel(
            name="DeliveryPointType",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(db_index=True, max_length=50, unique=True)),
                ("name", models.CharField(max_length=100)),
                ("is_carrier", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("sort_order", models.PositiveIntegerField(default=0)),
            ],
            options={"ordering": ["sort_order", "name"]},
        ),
        migrations.CreateModel(
            name="DeliveryPointChannel",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("idx", models.CharField(max_length=128, unique=True)),
                ("name", models.CharField(blank=True, default="", max_length=128)),
                (
                    "default_language",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="dp_default_channels",
                        to="django_regional.language",
                    ),
                ),
                (
                    "languages",
                    models.ManyToManyField(blank=True, related_name="dp_channels", to="django_regional.language"),
                ),
            ],
            options={"ordering": ["name"]},
        ),
        migrations.CreateModel(
            name="DeliveryPoint",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(db_index=True, max_length=100)),
                ("name", models.CharField(max_length=200)),
                ("latitude", models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ("longitude", models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ("street", models.CharField(blank=True, default="", max_length=200)),
                ("city", models.CharField(blank=True, db_index=True, default="", max_length=100)),
                ("state", models.CharField(blank=True, default="", max_length=100)),
                ("post_code", models.CharField(blank=True, db_index=True, default="", max_length=20)),
                ("country", models.CharField(blank=True, default="", max_length=2)),
                ("phone", models.CharField(blank=True, default="", max_length=50)),
                ("email", models.EmailField(blank=True, default="", max_length=254)),
                ("website", models.URLField(blank=True, default="")),
                ("opening_hours", models.CharField(blank=True, default="", max_length=255)),
                ("hint", models.TextField(blank=True, default="")),
                ("is_active", models.BooleanField(default=True)),
                (
                    "channels",
                    models.ManyToManyField(
                        blank=True, related_name="delivery_points", to="django_deliverypoints.deliverypointchannel"
                    ),
                ),
                (
                    "type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="points",
                        to="django_deliverypoints.deliverypointtype",
                    ),
                ),
            ],
            options={"ordering": ["name"]},
        ),
        migrations.CreateModel(
            name="ImportLog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("mode", models.CharField(max_length=20)),
                ("created_count", models.PositiveIntegerField(default=0)),
                ("updated_count", models.PositiveIntegerField(default=0)),
                ("disabled_count", models.PositiveIntegerField(default=0)),
                ("entries", models.JSONField(default=list)),
                ("source", models.CharField(max_length=10)),
                (
                    "channel",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="import_logs",
                        to="django_deliverypoints.deliverypointchannel",
                    ),
                ),
                (
                    "type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="import_logs",
                        to="django_deliverypoints.deliverypointtype",
                    ),
                ),
            ],
            options={"ordering": ["-created_at"]},
        ),
        migrations.CreateModel(
            name="DeliveryPointT9N",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(blank=True, default="", max_length=200)),
                ("hint", models.TextField(blank=True, default="")),
                ("opening_hours", models.CharField(blank=True, default="", max_length=255)),
                (
                    "language",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="+", to="django_regional.language"
                    ),
                ),
                (
                    "point",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="translations",
                        to="django_deliverypoints.deliverypoint",
                    ),
                ),
            ],
            options={
                "constraints": [models.UniqueConstraint(fields=("point", "language"), name="unique_point_language")]
            },
        ),
        migrations.AddIndex(
            model_name="deliverypoint", index=models.Index(fields=["type", "is_active"], name="idx_type_active")
        ),
        migrations.AddIndex(
            model_name="deliverypoint", index=models.Index(fields=["latitude", "longitude"], name="idx_coordinates")
        ),
        migrations.AddConstraint(
            model_name="deliverypoint",
            constraint=models.UniqueConstraint(fields=("type", "code"), name="unique_type_code"),
        ),
    ]
